### ISSUE TITLE
Alpha values

### ISSUE THREAD

**Issue by jacobmischka** [noeldelgado/values.js#4]
Are there any plans to include rgba/hsla support?

**Comment by noeldelgado** [comment]
Hi @jacobmischka, I hadn't thought about that, but it seems a cool idea. 
If you have any comments about the implementation/usage please fell free to share them.
I will try to give it a try as soon as possible.

**Comment by jacobmischka** [comment]
I actually wound up using [Qix-/color](https://github.com/qix-/color) because it already supports alpha, so please don't rush to add this on my behalf. I do think it would be a useful addition though.

Thanks for the response!

**Comment by noeldelgado** [comment]
No problem Jacob, it may be fun to play with this though.

Thanks!
